---
name: build

on:
  push

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
    - name: Build
      run: make -j dist
    - name: List output
      run: ls -la build
